/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.FastPay.view;

/**
 *
 * @author HP
 */
public class FrmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdmin
     */
    public FrmAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGreeting = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        btnAddProducts = new javax.swing.JButton();
        btnSuppliersList = new javax.swing.JButton();
        btnDeleteUsers = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtGreeting.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtGreeting.setText("Eres parte de nuestro equipo.");

        txtQuestion.setText("¿Qué deseas hacer?");

        btnAddUser.setText("Añadir usuarios");

        btnAddProducts.setText("Añadir productos");

        btnSuppliersList.setText("Ver la lista de proveedores");

        btnDeleteUsers.setText("Borrar usuarios");

        btnExit.setText("Salir");

        txtWelcome.setFont(new java.awt.Font("MS PGothic", 1, 48)); // NOI18N
        txtWelcome.setText("Bienvenido!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuppliersList)
                    .addComponent(btnAddProducts)
                    .addComponent(btnDeleteUsers)
                    .addComponent(btnExit)
                    .addComponent(txtGreeting)
                    .addComponent(btnAddUser)
                    .addComponent(txtWelcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtGreeting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(txtQuestion)
                .addGap(18, 18, 18)
                .addComponent(btnAddUser)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteUsers)
                .addGap(18, 18, 18)
                .addComponent(btnAddProducts)
                .addGap(18, 18, 18)
                .addComponent(btnSuppliersList)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      /*txtGreetingawt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdmin().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProducts;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDeleteUsers;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSuppliersList;
    private javax.swing.JLabel txtGreeting;
    private javax.swing.JLabel txtQuestion;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
