
package ec.edu.espe.FastPay.view;
import ec.edu.espe.FastPay.model.Cargar;
import java.awt.Image;
import java.awt.Toolkit;





public final class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    Cargar hilo;

    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        iniciar();

    }
    
    
    
     public Image getIconImageH(){
         Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("C:/Users/Lenovo/Desktop/Proyecto-master/03 Codigo/FastPay/src/ec/edu/espe/imagenes/FastPay.png"));
         return retValue;
     }


    public void iniciar() {
        setLocationRelativeTo(null);
        hilo = new Cargar(getProgress());
        hilo.start();
        hilo = null;
        this.setLocationRelativeTo(null);

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labLogo = new javax.swing.JLabel();
        prgssLoadingBar = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        txtBackSquad = new javax.swing.JLabel();
        labBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(600, 376));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/imagenes/logo.jpg"))); // NOI18N
        getContentPane().add(labLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 300, 340));

        prgssLoadingBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                prgssLoadingBarStateChanged(evt);
            }
        });
        getContentPane().add(prgssLoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 494, 25));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        txtBackSquad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtBackSquad.setForeground(new java.awt.Color(255, 255, 255));
        txtBackSquad.setText("DISEÑADO POR: BACKSQUAD");
        jPanel1.add(txtBackSquad);
        txtBackSquad.setBounds(180, 0, 320, 20);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 514, 27));

        labBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/imagenes/tienda.jpg"))); // NOI18N
        labBack.setText("jLabel4");
        getContentPane().add(labBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -20, 990, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prgssLoadingBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_prgssLoadingBarStateChanged
        if (prgssLoadingBar.getValue() == 100) {
            
            frmLogin vp = new frmLogin();
            vp.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_prgssLoadingBarStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labBack;
    private javax.swing.JLabel labLogo;
    private javax.swing.JProgressBar prgssLoadingBar;
    private javax.swing.JLabel txtBackSquad;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the progress
     */
    public javax.swing.JProgressBar getProgress() {
        return prgssLoadingBar;
    }

    
   
}
