/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.FastPay.view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmUser extends javax.swing.JFrame {

    /**
     * Creates new form FrmUser
     */
    public FrmUser() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/ec/edu/espe/imagenes/logo.png")).getImage());
        this.TablaUser.setModel(modelo);
        this.modelo.addColumn("ID");
        this.modelo.addColumn("Name");
        this.modelo.addColumn("User");
        this.modelo.addColumn("Password");
        this.modelo.addColumn("TypeUser");

        this.setTitle("User Registration");
        this.setLocation(400, 220);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    DefaultTableModel modelo = new DefaultTableModel();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUser = new javax.swing.JTable();
        txtIdText = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNameText = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUserText = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPasswordText = new javax.swing.JLabel();
        txtTypeUser = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cmbPosition = new javax.swing.JComboBox<String>();
        btnSave = new javax.swing.JButton();
        btNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaUser);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 560, 80));

        txtIdText.setText("ID");
        txtIdText.setToolTipText("ID del usuario");
        getContentPane().add(txtIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtId.setToolTipText("Ingrese aquí ID para registrar al nuevo usuario");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, -1));

        txtNameText.setText("Nombre");
        txtNameText.setToolTipText("Nombre del usuario");
        getContentPane().add(txtNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtName.setToolTipText("Ingrese aquí el nombre del usuario");
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 150, -1));

        txtUserText.setText("Usuario");
        txtUserText.setToolTipText("Nombre de como se registra al usuario al sistema");
        getContentPane().add(txtUserText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtUser.setToolTipText("Ingrese aquí el nombre de como se registra al usuario al sistema");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 130, -1));

        txtPasswordText.setText("Contraseña");
        txtPasswordText.setToolTipText("Contraseña que se le asignará al nuevo usuario");
        getContentPane().add(txtPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txtTypeUser.setText("Tipo de Usuario");
        txtTypeUser.setToolTipText("Tipo de usuario");
        getContentPane().add(txtTypeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtPassword.setToolTipText("Ingrese aquí la contraseña para el nuevo usuario");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 120, -1));

        cmbPosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Administrador" }));
        cmbPosition.setToolTipText("Elija el tipo de usuario que se va a ingresar");
        cmbPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPositionActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, -1));

        btnSave.setText("Guardar");
        btnSave.setToolTipText("Presione aquí para guardar al nuevo usuario");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 120, -1));

        btNew.setText("Nuevo");
        btNew.setToolTipText("Presione aquí para crear un nuevo usuario");
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });
        getContentPane().add(btNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 120, -1));

        btnEdit.setText("Editar");
        btnEdit.setToolTipText("Presione aquí para editar un usuario");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 120, -1));

        btnDelete.setText("Borrar");
        btnDelete.setToolTipText("Presione aquí para borrar un usuario");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 120, -1));

        btnExit.setText("Atrás");
        btnExit.setToolTipText("Presione aquí para regresar al menú anterior");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 610, 430));

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void cmbPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPositionActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        this.modelo.addRow(new Object[]{this.txtId.getText(), this.txtName.getText(),
            this.cmbPosition.getSelectedItem(), this.txtUser.getText(), this.txtPassword.getText()});
        this.txtId.setText("");
        this.txtName.setText("");
        this.cmbPosition.setSelectedIndex(0);
        this.txtUser.setText("");
        this.txtPassword.setText("");
        txtId.grabFocus();


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        // TODO add your handling code here:
        this.txtId.setText("");
        this.txtName.setText("");
        this.cmbPosition.setSelectedIndex(0);
        this.txtUser.setText("");
        this.txtPassword.setText("");

    }//GEN-LAST:event_btNewActionPerformed
    int filas;
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String[] datos = new String[5];
        datos[0] = txtId.getText();
        datos[1] = txtName.getText();
        datos[2] = this.cmbPosition.getSelectedItem().toString();
        datos[3] = txtUser.getText();
        datos[4] = txtPassword.getText();

        for (int i = 0; i < TablaUser.getColumnCount(); i++) {
            modelo.setValueAt(datos[i], filas, i);
        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int fila_selecionada = TablaUser.getSelectedRow();
        if (fila_selecionada >= 0) {
            modelo.removeRow(fila_selecionada);

        } else {
            JOptionPane.showMessageDialog(null, "Select one row plis");

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void TablaUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUserMouseClicked
        // TODO add your handling code here:
        int fila_seleccionada = TablaUser.getSelectedRow();
        txtId.setText(TablaUser.getValueAt(fila_seleccionada, 0).toString());
        txtName.setText(TablaUser.getValueAt(fila_seleccionada, 1).toString());
        cmbPosition.setSelectedItem(TablaUser.getValueAt(fila_seleccionada, 2).toString());
        txtUser.setText(TablaUser.getValueAt(fila_seleccionada, 3).toString());
        txtPassword.setText(TablaUser.getValueAt(fila_seleccionada, 4).toString());
        filas = fila_seleccionada;
    }//GEN-LAST:event_TablaUserMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaUser;
    private javax.swing.JButton btNew;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtId;
    private javax.swing.JLabel txtIdText;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel txtNameText;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JLabel txtPasswordText;
    private javax.swing.JLabel txtTypeUser;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel txtUserText;
    // End of variables declaration//GEN-END:variables
}
